class MockData {
  // 1. Data Profil Siswa Utama (Faizullatif Fajran - MAN 2 Kota Padang)
  static const Map<String, dynamic> studentProfile = {
    'id': 'usr_991823ab',
    'nisn': '3171012345670001',
    'name': 'Faizullatif Fajran',
    'school': 'MAN 2 Kota Padang',
    'classGrade': 'XII.FA-3',
    'allergies': ['Kacang Tanah', 'Udang'],
    'phone': '081234567890',
  };

  // 2. Data Statistik Ringkasan Dasbor Siswa (Bulan Agustus 2026)
  static const Map<String, dynamic> studentDashboardStats = {
    'totalPortionsReceived': 18,
    'attendancePercentage': 95.0,
    'totalEvaluationsSubmitted': 16,
    'currentDateFormatted': 'Sabtu, 8 Agustus 2026',
  };

  // 3. Master Daftar 15 Katalog Menu MBG Lengkap & Relasional
  static const List<Map<String, dynamic>> foodMenuList = [
    {
      'id_menu': 'mnu_441209cc',
      'nama_menu': 'Nasi Ayam Bakar Kecap & Tumis Buncis',
      'name': 'Nasi Ayam Bakar Kecap & Tumis Buncis',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 550,
      'calories': 550,
      'protein_gram': 28.5,
      'protein': '28.5g',
      'karbohidrat_gram': 65.0,
      'lemak_gram': 14.2,
      'komposisi_bahan': ['Dada Ayam Bakar Kecap', 'Tumis Buncis & Wortel', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {'nama': 'Dada Ayam Bakar Kecap', 'sub': 'Sumber Utama Protein & Zat Besi', 'berat': '80 gram'},
        {'nama': 'Tumis Buncis & Wortel', 'sub': 'Kaya Serat & Vitamin A', 'berat': '60 gram'},
        {'nama': 'Nasi Putih Warm', 'sub': 'Karbohidrat Kompleks', 'berat': '150 gram'},
      ],
      'potensi_alergen': ['Kedelai'],
      'foto_url': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.9,
      'tanggal_jadwal': 'Sabtu, 8 Agustus 2026',
    },
    {
      'id_menu': 'mnu_551902aa',
      'nama_menu': 'Nasi Semur Daging Sapi & Sup Sayur',
      'name': 'Nasi Semur Daging Sapi & Sup Sayur',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 580,
      'calories': 580,
      'protein_gram': 32.0,
      'protein': '32g',
      'karbohidrat_gram': 60.0,
      'lemak_gram': 15.0,
      'komposisi_bahan': ['Daging Sapi Semur Empuk', 'Sup Brokoli & Wortel', 'Telur Rebus Organik', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {'nama': 'Daging Sapi Semur Empuk', 'sub': 'Kaya Asam Amino & Protein Sapi', 'berat': '90 gram'},
        {'nama': 'Sup Brokoli & Wortel', 'sub': 'Antioksidan & Mineral Alami', 'berat': '70 gram'},
        {'nama': 'Telur Rebus Organik', 'sub': 'Sumber Kolin & B12', 'berat': '50 gram'},
        {'nama': 'Nasi Putih Warm', 'sub': 'Karbohidrat Kompleks', 'berat': '150 gram'},
      ],
      'potensi_alergen': ['Kedelai', 'Telur'],
      'foto_url': 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.8,
      'tanggal_jadwal': 'Senin, 10 Agustus 2026',
    },
    {
      'id_menu': 'mnu_662011bb',
      'nama_menu': 'Nasi Ikan Kembung Bakar & Tumis Bayam',
      'name': 'Nasi Ikan Kembung Bakar & Tumis Bayam',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 440,
      'calories': 440,
      'protein_gram': 30.0,
      'protein': '30g',
      'karbohidrat_gram': 52.0,
      'lemak_gram': 10.0,
      'komposisi_bahan': ['Ikan Kembung Bakar', 'Tumis Bayam & Jagung', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {'nama': 'Ikan Kembung Bakar', 'sub': 'Tinggi Omega-3 & DHA', 'berat': '85 gram'},
        {'nama': 'Tumis Bayam & Jagung', 'sub': 'Asam Folat & Zat Besi', 'berat': '65 gram'},
        {'nama': 'Nasi Putih Warm', 'sub': 'Karbohidrat Utama', 'berat': '150 gram'},
      ],
      'potensi_alergen': ['Ikan Laut'],
      'foto_url': 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.7,
      'tanggal_jadwal': 'Selasa, 11 Agustus 2026',
    },
    {
      'id_menu': 'mnu_773122cc',
      'nama_menu': 'Nasi Rolade Sapi & Capcay Sayur Segar',
      'name': 'Nasi Rolade Sapi & Capcay Sayur Segar',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 520,
      'calories': 520,
      'protein_gram': 26.0,
      'protein': '26g',
      'karbohidrat_gram': 58.0,
      'lemak_gram': 12.5,
      'komposisi_bahan': ['Rolade Daging Sapi', 'Capcay Sayur Kombinasi', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {'nama': 'Rolade Daging Sapi', 'sub': 'Protein Olahan Berkualitas', 'berat': '80 gram'},
        {'nama': 'Capcay Sayur Kombinasi', 'sub': 'Kembang Kol, Wortel & Sawi', 'berat': '70 gram'},
        {'nama': 'Nasi Putih Warm', 'sub': 'Karbohidrat Utama', 'berat': '150 gram'},
      ],
      'potensi_alergen': ['Telur', 'Kedelai'],
      'foto_url': 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.8,
      'tanggal_jadwal': 'Rabu, 12 Agustus 2026',
    },
    {
      'id_menu': 'mnu_884233dd',
      'nama_menu': 'Nasi Ayam Goreng Lengkuas & Tahu Tempe',
      'name': 'Nasi Ayam Goreng Lengkuas & Tahu Tempe',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 560,
      'calories': 560,
      'protein_gram': 29.0,
      'protein': '29g',
      'karbohidrat_gram': 62.0,
      'lemak_gram': 16.0,
      'komposisi_bahan': ['Ayam Goreng Rempah Lengkuas', 'Tahu Tempe Bacem Kukus', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {'nama': 'Ayam Goreng Rempah Lengkuas', 'sub': 'Sumber Protein & Niacin', 'berat': '85 gram'},
        {'nama': 'Tahu Tempe Bacem Kukus', 'sub': 'Isoflavon & Protein Nabati', 'berat': '50 gram'},
        {'nama': 'Nasi Putih Warm', 'sub': 'Karbohidrat Kompleks', 'berat': '150 gram'},
      ],
      'potensi_alergen': ['Kedelai'],
      'foto_url': 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.9,
      'tanggal_jadwal': 'Kamis, 13 Agustus 2026',
    },
    {
      'id_menu': 'mnu_995344ee',
      'nama_menu': 'Nasi Telur Balado & Tumis Kacang Panjang',
      'name': 'Nasi Telur Balado & Tumis Kacang Panjang',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 480,
      'calories': 480,
      'protein_gram': 22.0,
      'protein': '22g',
      'karbohidrat_gram': 55.0,
      'lemak_gram': 11.0,
      'komposisi_bahan': ['Telur Rebus Organik', 'Tumis Kacang Panjang', 'Tahu Tempe Bacem Kukus', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {'nama': 'Telur Rebus Organik', 'sub': 'Protein Telur Utuh', 'berat': '60 gram'},
        {'nama': 'Tumis Kacang Panjang', 'sub': 'Serat & Vitamin B Kompleks', 'berat': '60 gram'},
        {'nama': 'Tahu Tempe Bacem Kukus', 'sub': 'Protein Nabati', 'berat': '40 gram'},
        {'nama': 'Nasi Putih Warm', 'sub': 'Karbohidrat Utama', 'berat': '150 gram'},
      ],
      'potensi_alergen': ['Telur', 'Kedelai'],
      'foto_url': 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.6,
      'tanggal_jadwal': 'Jumat, 14 Agustus 2026',
    },
    {
      'id_menu': 'mnu_101011ff',
      'nama_menu': 'Paket Pisang Ambon & Susu UHT Segar',
      'name': 'Paket Pisang Ambon & Susu UHT Segar',
      'kategori': 'SUSU_DAN_BUAH',
      'category': 'Susu & Buah',
      'kalori_kkal': 210,
      'calories': 210,
      'protein_gram': 7.0,
      'protein': '7g',
      'karbohidrat_gram': 38.0,
      'lemak_gram': 3.5,
      'komposisi_bahan': ['Buah Pisang Ambon Segar', 'Susu UHT Segar 200ml'],
      'komposisi_bahan_detail': [
        {'nama': 'Buah Pisang Ambon Segar', 'sub': 'Tinggi Kalium & Serat', 'berat': '100 gram'},
        {'nama': 'Susu UHT Segar 200ml', 'sub': 'Kalsium & Vitamin D', 'berat': '200 ml'},
      ],
      'potensi_alergen': ['Susu Sapi'],
      'foto_url': 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.9,
      'tanggal_jadwal': 'Sabtu, 15 Agustus 2026',
    },
    {
      'id_menu': 'mnu_111122gg',
      'nama_menu': 'Paket Buah Apel Merah & Susu Segar',
      'name': 'Paket Buah Apel Merah & Susu Segar',
      'kategori': 'SUSU_DAN_BUAH',
      'category': 'Susu & Buah',
      'kalori_kkal': 200,
      'calories': 200,
      'protein_gram': 6.5,
      'protein': '6.5g',
      'karbohidrat_gram': 36.0,
      'lemak_gram': 3.2,
      'komposisi_bahan': ['Buah Apel Merah Segar', 'Susu UHT Segar 200ml'],
      'komposisi_bahan_detail': [
        {'nama': 'Buah Apel Merah Segar', 'sub': 'Antioksidan & Pektin', 'berat': '110 gram'},
        {'nama': 'Susu UHT Segar 200ml', 'sub': 'Kalsium & Vitamin D', 'berat': '200 ml'},
      ],
      'potensi_alergen': ['Susu Sapi'],
      'foto_url': 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.8,
      'tanggal_jadwal': 'Senin, 17 Agustus 2026',
    },
    {
      'id_menu': 'mnu_121233hh',
      'nama_menu': 'Pudding Buah Mangga & Susu UHT',
      'name': 'Pudding Buah Mangga & Susu UHT',
      'kategori': 'SUSU_DAN_BUAH',
      'category': 'Susu & Buah',
      'kalori_kkal': 225,
      'calories': 225,
      'protein_gram': 6.8,
      'protein': '6.8g',
      'karbohidrat_gram': 40.0,
      'lemak_gram': 3.8,
      'komposisi_bahan': ['Pudding Buah Mangga', 'Susu UHT Segar 200ml'],
      'komposisi_bahan_detail': [
        {'nama': 'Pudding Buah Mangga', 'sub': 'Vitamin C & Serat Lembut', 'berat': '90 gram'},
        {'nama': 'Susu UHT Segar 200ml', 'sub': 'Kalsium Alami', 'berat': '200 ml'},
      ],
      'potensi_alergen': ['Susu Sapi'],
      'foto_url': 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.8,
      'tanggal_jadwal': 'Selasa, 18 Agustus 2026',
    },
    {
      'id_menu': 'mnu_131344ii',
      'nama_menu': 'Bubur Kacang Hijau Organik & Roti Gandum',
      'name': 'Bubur Kacang Hijau Organik & Roti Gandum',
      'kategori': 'SNACK_SEHAT',
      'category': 'Snack Sehat',
      'kalori_kkal': 310,
      'calories': 310,
      'protein_gram': 12.0,
      'protein': '12g',
      'karbohidrat_gram': 56.0,
      'lemak_gram': 4.5,
      'komposisi_bahan': ['Bubur Kacang Hijau Organik', 'Roti Gandum Utuh'],
      'komposisi_bahan_detail': [
        {'nama': 'Bubur Kacang Hijau Organik', 'sub': 'Asam Folat & Zink', 'berat': '150 gram'},
        {'nama': 'Roti Gandum Utuh', 'sub': 'Serat Karbo Kompleks', 'berat': '40 gram'},
      ],
      'potensi_alergen': ['Gandum'],
      'foto_url': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.7,
      'tanggal_jadwal': 'Rabu, 19 Agustus 2026',
    },
    {
      'id_menu': 'mnu_141455jj',
      'nama_menu': 'Sandwich Dada Ayam & Roti Gandum',
      'name': 'Sandwich Dada Ayam & Roti Gandum',
      'kategori': 'SNACK_SEHAT',
      'category': 'Snack Sehat',
      'kalori_kkal': 340,
      'calories': 340,
      'protein_gram': 18.5,
      'protein': '18.5g',
      'karbohidrat_gram': 48.0,
      'lemak_gram': 7.2,
      'komposisi_bahan': ['Roti Gandum Utuh', 'Dada Ayam Bakar Kecap', 'Tumis Buncis & Wortel'],
      'komposisi_bahan_detail': [
        {'nama': 'Roti Gandum Utuh', 'sub': 'Karbohidrat Kompleks', 'berat': '50 gram'},
        {'nama': 'Dada Ayam Bakar Kecap', 'sub': 'Protein Unggas', 'berat': '60 gram'},
        {'nama': 'Tumis Buncis & Wortel', 'sub': 'Sayur Segar', 'berat': '30 gram'},
      ],
      'potensi_alergen': ['Gandum', 'Kedelai'],
      'foto_url': 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.8,
      'tanggal_jadwal': 'Kamis, 20 Agustus 2026',
    },
    {
      'id_menu': 'mnu_151566kk',
      'nama_menu': 'Nasi Soto Ayam Kuning & Perkedel',
      'name': 'Nasi Soto Ayam Kuning & Perkedel',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 510,
      'calories': 510,
      'protein_gram': 27.0,
      'protein': '27g',
      'karbohidrat_gram': 60.0,
      'lemak_gram': 13.0,
      'komposisi_bahan': ['Ayam Goreng Rempah Lengkuas', 'Sup Brokoli & Wortel', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {'nama': 'Ayam Goreng Rempah Lengkuas', 'sub': 'Suwiran Ayam Soto', 'berat': '75 gram'},
        {'nama': 'Sup Brokoli & Wortel', 'sub': 'Kuah Soto & Sayur', 'berat': '70 gram'},
        {'nama': 'Nasi Putih Warm', 'sub': 'Karbohidrat Utama', 'berat': '150 gram'},
      ],
      'potensi_alergen': [],
      'foto_url': 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.7,
      'tanggal_jadwal': 'Jumat, 21 Agustus 2026',
    },
    {
      'id_menu': 'mnu_161677ll',
      'nama_menu': 'Nasi Ikan Gurame Asam Manis & Sup Sayur',
      'name': 'Nasi Ikan Gurame Asam Manis & Sup Sayur',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 580,
      'calories': 580,
      'protein_gram': 31.0,
      'protein': '31g',
      'karbohidrat_gram': 64.0,
      'lemak_gram': 14.0,
      'komposisi_bahan': ['Ikan Kembung Bakar', 'Sup Brokoli & Wortel', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {'nama': 'Ikan Kembung Bakar', 'sub': 'Fillet Ikan Gurame Asam Manis', 'berat': '85 gram'},
        {'nama': 'Sup Brokoli & Wortel', 'sub': 'Sayuran Sup Segar', 'berat': '70 gram'},
        {'nama': 'Nasi Putih Warm', 'sub': 'Karbohidrat Utama', 'berat': '150 gram'},
      ],
      'potensi_alergen': ['Ikan Laut'],
      'foto_url': 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.6,
      'tanggal_jadwal': 'Sabtu, 22 Agustus 2026',
    },
    {
      'id_menu': 'mnu_171788mm',
      'nama_menu': 'Nasi Tumis Cumi Cabe Hijau & Tahu',
      'name': 'Nasi Tumis Cumi Cabe Hijau & Tahu',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 460,
      'calories': 460,
      'protein_gram': 24.0,
      'protein': '24g',
      'karbohidrat_gram': 50.0,
      'lemak_gram': 11.5,
      'komposisi_bahan': ['Ikan Kembung Bakar', 'Tahu Tempe Bacem Kukus', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {'nama': 'Ikan Kembung Bakar', 'sub': 'Cumi Olahan Rempah', 'berat': '75 gram'},
        {'nama': 'Tahu Tempe Bacem Kukus', 'sub': 'Tahu Goreng', 'berat': '40 gram'},
        {'nama': 'Nasi Putih Warm', 'sub': 'Karbohidrat Utama', 'berat': '150 gram'},
      ],
      'potensi_alergen': ['Ikan Laut', 'Kedelai'],
      'foto_url': 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.2,
      'tanggal_jadwal': 'Senin, 24 Agustus 2026',
    },
    {
      'id_menu': 'mnu_181899nn',
      'nama_menu': 'Nasi Sayur Nangka & Sambal Goreng Ati',
      'name': 'Nasi Sayur Nangka & Sambal Goreng Ati',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 490,
      'calories': 490,
      'protein_gram': 21.0,
      'protein': '21g',
      'karbohidrat_gram': 54.0,
      'lemak_gram': 13.5,
      'komposisi_bahan': ['Daging Sapi Semur Empuk', 'Capcay Sayur Kombinasi', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {'nama': 'Daging Sapi Semur Empuk', 'sub': 'Ati Sapi Olahan', 'berat': '70 gram'},
        {'nama': 'Capcay Sayur Kombinasi', 'sub': 'Sayur Nangka Santan', 'berat': '70 gram'},
        {'nama': 'Nasi Putih Warm', 'sub': 'Karbohidrat Utama', 'berat': '150 gram'},
      ],
      'potensi_alergen': ['Kedelai'],
      'foto_url': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
      'photoUrl': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 3.9,
      'tanggal_jadwal': 'Selasa, 25 Agustus 2026',
    },
  ];

  static Map<String, dynamic> get todayMenu => foodMenuList.first;
  static Map<String, dynamic> get tomorrowMenu => foodMenuList[1];

  static List<Map<String, String>> get masterHealthyIngredients =>
      masterHealthyIngredientsFull.map((item) {
        return {
          'nama': item['nama_bahan'].toString(),
          'sub': item['subjudul_nutrisi'].toString(),
          'berat': item['takaran_default'].toString(),
        };
      }).toList();

  // 4. Master 19 Bahan Baku Sehat Relasional
  static const List<Map<String, dynamic>> masterHealthyIngredientsFull = [
    {
      'id_bahan': 'bhn_10293847',
      'nama_bahan': 'Dada Ayam Bakar Kecap',
      'nama': 'Dada Ayam Bakar Kecap',
      'kategori_bahan': 'PROTEIN_HEWANI',
      'kategori': 'Protein Hewani',
      'subjudul_nutrisi': 'Sumber Utama Protein & Zat Besi',
      'sub': 'Sumber Utama Protein & Zat Besi',
      'takaran_default': '80 gram',
      'berat': '80 gram',
      'kalori_per_100g': 165,
      'potensi_alergen': ['Kedelai'],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293848',
      'nama_bahan': 'Daging Sapi Semur Empuk',
      'nama': 'Daging Sapi Semur Empuk',
      'kategori_bahan': 'PROTEIN_HEWANI',
      'kategori': 'Protein Hewani',
      'subjudul_nutrisi': 'Kaya Asam Amino & Protein Sapi',
      'sub': 'Kaya Asam Amino & Protein Sapi',
      'takaran_default': '90 gram',
      'berat': '90 gram',
      'kalori_per_100g': 250,
      'potensi_alergen': ['Kedelai'],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293849',
      'nama_bahan': 'Ikan Kembung Bakar',
      'nama': 'Ikan Kembung Bakar',
      'kategori_bahan': 'PROTEIN_HEWANI',
      'kategori': 'Protein Hewani',
      'subjudul_nutrisi': 'Tinggi Asam Lemak Omega-3 & DHA',
      'sub': 'Tinggi Asam Lemak Omega-3 & DHA',
      'takaran_default': '85 gram',
      'berat': '85 gram',
      'kalori_per_100g': 140,
      'potensi_alergen': ['Ikan Laut'],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293850',
      'nama_bahan': 'Telur Rebus Organik',
      'nama': 'Telur Rebus Organik',
      'kategori_bahan': 'PROTEIN_HEWANI',
      'kategori': 'Protein Hewani',
      'subjudul_nutrisi': 'Sumber Kolin, Vitamin B12, & Lemak Sehat',
      'sub': 'Sumber Kolin, Vitamin B12, & Lemak Sehat',
      'takaran_default': '50 gram',
      'berat': '50 gram',
      'kalori_per_100g': 155,
      'potensi_alergen': ['Telur'],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293851',
      'nama_bahan': 'Rolade Daging Sapi',
      'nama': 'Rolade Daging Sapi',
      'kategori_bahan': 'PROTEIN_HEWANI',
      'kategori': 'Protein Hewani',
      'subjudul_nutrisi': 'Protein Sapi Cincang Olahan Berkualitas',
      'sub': 'Protein Sapi Cincang Olahan Berkualitas',
      'takaran_default': '80 gram',
      'berat': '80 gram',
      'kalori_per_100g': 210,
      'potensi_alergen': ['Telur', 'Kedelai'],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293852',
      'nama_bahan': 'Ayam Goreng Rempah Lengkuas',
      'nama': 'Ayam Goreng Rempah Lengkuas',
      'kategori_bahan': 'PROTEIN_HEWANI',
      'kategori': 'Protein Hewani',
      'subjudul_nutrisi': 'Sumber Protein Unggas & Rempah Alami',
      'sub': 'Sumber Protein Unggas & Rempah Alami',
      'takaran_default': '85 gram',
      'berat': '85 gram',
      'kalori_per_100g': 220,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293853',
      'nama_bahan': 'Tahu Tempe Bacem Kukus',
      'nama': 'Tahu Tempe Bacem Kukus',
      'kategori_bahan': 'PROTEIN_NABATI',
      'kategori': 'Protein Nabati',
      'subjudul_nutrisi': 'Isoflavon, Serat, & Protein Kedelai',
      'sub': 'Isoflavon, Serat, & Protein Kedelai',
      'takaran_default': '60 gram',
      'berat': '60 gram',
      'kalori_per_100g': 140,
      'potensi_alergen': ['Kedelai'],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293854',
      'nama_bahan': 'Nasi Putih Warm',
      'nama': 'Nasi Putih Warm',
      'kategori_bahan': 'KARBOHIDRAT',
      'kategori': 'Karbohidrat Utama',
      'subjudul_nutrisi': 'Sumber Energi Karbohidrat Kompleks',
      'sub': 'Sumber Energi Karbohidrat Kompleks',
      'takaran_default': '150 gram',
      'berat': '150 gram',
      'kalori_per_100g': 130,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293855',
      'nama_bahan': 'Tumis Buncis & Wortel',
      'nama': 'Tumis Buncis & Wortel',
      'kategori_bahan': 'SAYUR_DAN_BUAH',
      'kategori': 'Sayur & Buah',
      'subjudul_nutrisi': 'Kaya Serat Pangan & Vitamin A',
      'sub': 'Kaya Serat Pangan & Vitamin A',
      'takaran_default': '60 gram',
      'berat': '60 gram',
      'kalori_per_100g': 45,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293856',
      'nama_bahan': 'Sup Brokoli & Wortel',
      'nama': 'Sup Brokoli & Wortel',
      'kategori_bahan': 'SAYUR_DAN_BUAH',
      'kategori': 'Sayur & Buah',
      'subjudul_nutrisi': 'Antioksidan Alami & Vitamin C',
      'sub': 'Antioksidan Alami & Vitamin C',
      'takaran_default': '70 gram',
      'berat': '70 gram',
      'kalori_per_100g': 35,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293857',
      'nama_bahan': 'Tumis Bayam & Jagung',
      'nama': 'Tumis Bayam & Jagung',
      'kategori_bahan': 'SAYUR_DAN_BUAH',
      'kategori': 'Sayur & Buah',
      'subjudul_nutrisi': 'Zat Besi, Asam Folat, & Lutein',
      'sub': 'Zat Besi, Asam Folat, & Lutein',
      'takaran_default': '65 gram',
      'berat': '65 gram',
      'kalori_per_100g': 50,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293858',
      'nama_bahan': 'Capcay Sayur Kombinasi',
      'nama': 'Capcay Sayur Kombinasi',
      'kategori_bahan': 'SAYUR_DAN_BUAH',
      'kategori': 'Sayur & Buah',
      'subjudul_nutrisi': 'Kembang Kol, Sawi, & Wortel Segar',
      'sub': 'Kembang Kol, Sawi, & Wortel Segar',
      'takaran_default': '70 gram',
      'berat': '70 gram',
      'kalori_per_100g': 40,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293859',
      'nama_bahan': 'Tumis Kacang Panjang',
      'nama': 'Tumis Kacang Panjang',
      'kategori_bahan': 'SAYUR_DAN_BUAH',
      'kategori': 'Sayur & Buah',
      'subjudul_nutrisi': 'Kandungan Serat & B Kompleks',
      'sub': 'Kandungan Serat & B Kompleks',
      'takaran_default': '60 gram',
      'berat': '60 gram',
      'kalori_per_100g': 42,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293860',
      'nama_bahan': 'Buah Pisang Ambon Segar',
      'nama': 'Buah Pisang Ambon Segar',
      'kategori_bahan': 'SAYUR_DAN_BUAH',
      'kategori': 'Sayur & Buah',
      'subjudul_nutrisi': 'Kalium Alami & Energi Segar',
      'sub': 'Kalium Alami & Energi Segar',
      'takaran_default': '100 gram',
      'berat': '100 gram',
      'kalori_per_100g': 89,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293861',
      'nama_bahan': 'Buah Apel Merah Segar',
      'nama': 'Buah Apel Merah Segar',
      'kategori_bahan': 'SAYUR_DAN_BUAH',
      'kategori': 'Sayur & Buah',
      'subjudul_nutrisi': 'Antioksidan Pektin & Serat Buah',
      'sub': 'Antioksidan Pektin & Serat Buah',
      'takaran_default': '110 gram',
      'berat': '110 gram',
      'kalori_per_100g': 52,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293862',
      'nama_bahan': 'Pudding Buah Mangga',
      'nama': 'Pudding Buah Mangga',
      'kategori_bahan': 'SAYUR_DAN_BUAH',
      'kategori': 'Sayur & Buah',
      'subjudul_nutrisi': 'Vitamin C & Serat Pektin Lembut',
      'sub': 'Vitamin C & Serat Pektin Lembut',
      'takaran_default': '90 gram',
      'berat': '90 gram',
      'kalori_per_100g': 80,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293863',
      'nama_bahan': 'Susu UHT Segar 200ml',
      'nama': 'Susu UHT Segar 200ml',
      'kategori_bahan': 'SUSU_DAN_PELENGKAP',
      'kategori': 'Susu & Pelengkap',
      'subjudul_nutrisi': 'Kalsium Tinggi & Vitamin D',
      'sub': 'Kalsium Tinggi & Vitamin D',
      'takaran_default': '200 ml',
      'berat': '200 ml',
      'kalori_per_100g': 60,
      'potensi_alergen': ['Susu Sapi'],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293864',
      'nama_bahan': 'Bubur Kacang Hijau Organik',
      'nama': 'Bubur Kacang Hijau Organik',
      'kategori_bahan': 'PROTEIN_NABATI',
      'kategori': 'Protein Nabati',
      'subjudul_nutrisi': 'Asam Folat, Serat, & Zink Alami',
      'sub': 'Asam Folat, Serat, & Zink Alami',
      'takaran_default': '150 gram',
      'berat': '150 gram',
      'kalori_per_100g': 110,
      'potensi_alergen': [],
      'stok': 'Tersedia',
    },
    {
      'id_bahan': 'bhn_10293865',
      'nama_bahan': 'Roti Gandum Utuh',
      'nama': 'Roti Gandum Utuh',
      'kategori_bahan': 'KARBOHIDRAT',
      'kategori': 'Karbohidrat Utama',
      'subjudul_nutrisi': 'Serat Karbohidrat Kompleks Gandum',
      'sub': 'Serat Karbohidrat Kompleks Gandum',
      'takaran_default': '40 gram',
      'berat': '40 gram',
      'kalori_per_100g': 240,
      'potensi_alergen': ['Gandum'],
      'stok': 'Tersedia',
    },
  ];

  // 5. Master Data Rekomendasi TOPSIS SPK (15 Menu Katalog MBG 100% Relasional)
  static const List<Map<String, dynamic>> topsisRecommendations = [
    {
      'id': 'rec_01',
      'nama_menu': 'Nasi Ayam Bakar Kecap & Tumis Buncis',
      'kategori': 'Makanan Berat',
      'kalori': '550 kcal',
      'skor_kepuasan': '96.5%',
      'kepuasan_num': 96.5,
      'skor_rasa': 4.9,
      'skor_kesukaan': 4.9,
      'skor_porsi': 4.8,
      'sisa_makanan_pct': 4.2,
      'penolakan_pct': 2.1,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit Utama (Sangat Disukai Siswa)',
      'idss_insight': 'Berdasarkan survei 425 siswa, rasa gurih bakar kecap mencapai rating 4.9/5. Sisa makanan sangat rendah (4.2%). Sangat direkomendasikan disajikan rutin.',
      'ulasan_singkat': 'Favorit utama siswa, bumbu meresap & porsi sangat pas.',
    },
    {
      'id': 'rec_02',
      'nama_menu': 'Paket Pisang Ambon & Susu UHT Segar',
      'kategori': 'Susu & Buah',
      'kalori': '210 kcal',
      'skor_kepuasan': '95.8%',
      'kepuasan_num': 95.8,
      'skor_rasa': 4.9,
      'skor_kesukaan': 4.9,
      'skor_porsi': 4.9,
      'sisa_makanan_pct': 2.0,
      'penolakan_pct': 1.5,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Suplemen Favorit (Habis 100%)',
      'idss_insight': 'Kombinasi susu UHT dan pisang segar sangat disukai siswa. Tingkat konsumsi mencapai 98% dengan sisa makanan mendekati 0%.',
      'ulasan_singkat': 'Segar, bernutrisi, dan habis dikonsumsi seluruh siswa.',
    },
    {
      'id': 'rec_03',
      'nama_menu': 'Nasi Semur Daging Sapi & Sup Sayur',
      'kategori': 'Makanan Berat',
      'kalori': '580 kcal',
      'skor_kepuasan': '94.0%',
      'kepuasan_num': 94.0,
      'skor_rasa': 4.8,
      'skor_kesukaan': 4.8,
      'skor_porsi': 4.7,
      'sisa_makanan_pct': 5.0,
      'penolakan_pct': 3.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Penerimaan Tinggi)',
      'idss_insight': 'Tingkat kecukupan protein tinggi (32g). Kombinasi daging empuk dan sup brokoli segar disukai 94% siswa.',
      'ulasan_singkat': 'Daging empuk, sisa makanan sangat rendah di sekolah.',
    },
    {
      'id': 'rec_04',
      'nama_menu': 'Paket Buah Apel Merah & Susu Segar',
      'kategori': 'Susu & Buah',
      'kalori': '200 kcal',
      'skor_kepuasan': '93.2%',
      'kepuasan_num': 93.2,
      'skor_rasa': 4.8,
      'skor_kesukaan': 4.8,
      'skor_porsi': 4.8,
      'sisa_makanan_pct': 3.5,
      'penolakan_pct': 2.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Suplemen Favorit',
      'idss_insight': 'Apel merah rimbun dan susu segar memberikan energi tambahan yang sangat diminati siswa saat istirahat.',
      'ulasan_singkat': 'Apel manisan segar & susu kalsium tinggi.',
    },
    {
      'id': 'rec_05',
      'nama_menu': 'Nasi Ayam Goreng Lengkuas & Tahu Tempe',
      'kategori': 'Makanan Berat',
      'kalori': '560 kcal',
      'skor_kepuasan': '91.5%',
      'kepuasan_num': 91.5,
      'skor_rasa': 4.9,
      'skor_kesukaan': 4.7,
      'skor_porsi': 4.6,
      'sisa_makanan_pct': 5.5,
      'penolakan_pct': 3.5,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Penerimaan Sangat Baik)',
      'idss_insight': 'Rempah gurih lengkuas sangat diminati siswa. Tahu tempe bacem memberikan keseimbangan protein nabati.',
      'ulasan_singkat': 'Ayam gurih renyah, tahu tempe bacem lembut.',
    },
    {
      'id': 'rec_06',
      'nama_menu': 'Nasi Rolade Sapi & Capcay Sayur Segar',
      'kategori': 'Makanan Berat',
      'kalori': '520 kcal',
      'skor_kepuasan': '89.0%',
      'kepuasan_num': 89.0,
      'skor_rasa': 4.8,
      'skor_kesukaan': 4.6,
      'skor_porsi': 4.5,
      'sisa_makanan_pct': 7.0,
      'penolakan_pct': 4.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Baik)',
      'idss_insight': 'Tekstur rolade ramah bagi siswa SD & SMP. Penilaian kepuasan stabil di angka 89%.',
      'ulasan_singkat': 'Rolade empuk, capcay segar tidak berbau langu.',
    },
    {
      'id': 'rec_07',
      'nama_menu': 'Pudding Buah Mangga & Susu UHT',
      'kategori': 'Susu & Buah',
      'kalori': '225 kcal',
      'skor_kepuasan': '88.5%',
      'kepuasan_num': 88.5,
      'skor_rasa': 4.8,
      'skor_kesukaan': 4.6,
      'skor_porsi': 4.6,
      'sisa_makanan_pct': 4.0,
      'penolakan_pct': 2.5,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Dessert Nutrisi Favorit',
      'idss_insight': 'Pudding mangga dengan serat alami dan susu UHT merupakan pencuci mulut sehat yang paling dinanti siswa.',
      'ulasan_singkat': 'Pudding lembut manis buah asli & susu segar.',
    },
    {
      'id_menu': 'rec_08',
      'nama_menu': 'Sandwich Dada Ayam & Roti Gandum',
      'kategori': 'Snack Sehat',
      'kalori': '340 kcal',
      'skor_kepuasan': '87.0%',
      'kepuasan_num': 87.0,
      'skor_rasa': 4.8,
      'skor_kesukaan': 4.5,
      'skor_porsi': 4.5,
      'sisa_makanan_pct': 6.0,
      'penolakan_pct': 3.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Snack Sehat Ringkas',
      'idss_insight': 'Sandwich gandum isi dada ayam bakar praktis dikonsumsi dan menjadi snack favorit siswa.',
      'ulasan_singkat': 'Roti gandum empuk & dada ayam bakar lezat.',
    },
    {
      'id': 'rec_09',
      'nama_menu': 'Nasi Ikan Kembung Bakar & Tumis Bayam',
      'kategori': 'Makanan Berat',
      'kalori': '440 kcal',
      'skor_kepuasan': '85.0%',
      'kepuasan_num': 85.0,
      'skor_rasa': 4.7,
      'skor_kesukaan': 4.4,
      'skor_porsi': 4.3,
      'sisa_makanan_pct': 8.0,
      'penolakan_pct': 4.5,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Cukup Baik)',
      'idss_insight': 'Sumber Omega-3 tinggi. Ikan kembung bebas duri tajam disukai siswa.',
      'ulasan_singkat': 'Kaya asam omega-3, bumbu bakar meresap.',
    },
    {
      'id': 'rec_10',
      'nama_menu': 'Bubur Kacang Hijau Organik & Roti Gandum',
      'kategori': 'Snack Sehat',
      'kalori': '310 kcal',
      'skor_kepuasan': '83.5%',
      'kepuasan_num': 83.5,
      'skor_rasa': 4.7,
      'skor_kesukaan': 4.3,
      'skor_porsi': 4.4,
      'sisa_makanan_pct': 7.5,
      'penolakan_pct': 4.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Snack Sehat Tradisional',
      'idss_insight': 'Kacang hijau organik kaya akan zat besi dan asam folat, sangat baik disajikan untuk kudapan pagi.',
      'ulasan_singkat': 'Bubur hangat manis sedang & pendamping roti gandum.',
    },
    {
      'id': 'rec_11',
      'nama_menu': 'Nasi Telur Balado & Tumis Kacang Panjang',
      'kategori': 'Makanan Berat',
      'kalori': '480 kcal',
      'skor_kepuasan': '79.5%',
      'kepuasan_num': 79.5,
      'skor_rasa': 4.6,
      'skor_kesukaan': 4.1,
      'skor_porsi': 4.0,
      'sisa_makanan_pct': 12.0,
      'penolakan_pct': 6.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Standar Bernutrisi',
      'idss_insight': 'Menu hemat bernutrisi tinggi. Tingkat kepedasan balado telah disesuaikan standar siswa.',
      'ulasan_singkat': 'Telur balado gurih, manis pedas pas di lidah.',
    },
    {
      'id': 'rec_12',
      'nama_menu': 'Nasi Soto Ayam Kuning & Perkedel',
      'kategori': 'Makanan Berat',
      'kalori': '510 kcal',
      'skor_kepuasan': '75.0%',
      'kepuasan_num': 75.0,
      'skor_rasa': 4.7,
      'skor_kesukaan': 3.9,
      'skor_porsi': 3.9,
      'sisa_makanan_pct': 14.5,
      'penolakan_pct': 7.5,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Standar Kuah',
      'idss_insight': 'Kuah soto hangat disukai saat musim hujan. Perkedel kentang menjadi pelengkap favorit.',
      'ulasan_singkat': 'Kuah soto segar, perkedel gurih dan lembut.',
    },
    {
      'id': 'rec_13',
      'nama_menu': 'Nasi Ikan Gurame Asam Manis & Sup Sayur',
      'kategori': 'Makanan Berat',
      'kalori': '580 kcal',
      'skor_kepuasan': '71.2%',
      'kepuasan_num': 71.2,
      'skor_rasa': 4.6,
      'skor_kesukaan': 3.8,
      'skor_porsi': 3.8,
      'sisa_makanan_pct': 16.0,
      'penolakan_pct': 8.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Standar Ikan',
      'idss_insight': 'Menu variasi ikan gurame segar. Saus asam manis perlu dikurangi keasamannya.',
      'ulasan_singkat': 'Ikan gurame renyah, saus asam manis segar.',
    },
    {
      'id': 'rec_14',
      'nama_menu': 'Nasi Tumis Cumi Cabe Hijau & Tahu',
      'kategori': 'Makanan Berat',
      'kalori': '460 kcal',
      'skor_kepuasan': '44.5%',
      'kepuasan_num': 44.5,
      'skor_rasa': 4.2,
      'skor_kesukaan': 2.8,
      'skor_porsi': 3.2,
      'sisa_makanan_pct': 28.5,
      'penolakan_pct': 16.0,
      'keputusan': 'MODIFIKASI_RESEP',
      'keputusanLabel': 'Perlu Evaluasi (Tingkat Kepuasan < 50%)',
      'idss_insight': 'Evaluasi IDSS: Kepuasan di bawah 50% (44.5%) dan sisa makanan tinggi (28.5%). Tekstur cumi terlalu kenyal & pedas bagi siswa.',
      'ulasan_singkat': 'Tekstur cumi agak kenyal, cabe hijau terlalu pedas.',
    },
    {
      'id': 'rec_15',
      'nama_menu': 'Nasi Sayur Nangka & Sambal Goreng Ati',
      'kategori': 'Makanan Berat',
      'kalori': '490 kcal',
      'skor_kepuasan': '35.2%',
      'kepuasan_num': 35.2,
      'skor_rasa': 3.9,
      'skor_kesukaan': 2.3,
      'skor_porsi': 3.1,
      'sisa_makanan_pct': 36.0,
      'penolakan_pct': 25.0,
      'keputusan': 'DIHAPUS_GANTI_MENU',
      'keputusanLabel': 'Perlu Evaluasi (Tingkat Kepuasan < 50%)',
      'idss_insight': 'Evaluasi IDSS: Kepuasan terendah (35.2%) dengan penolakan siswa 25%. Disarankan evaluasi total / ganti menu olahan ayam.',
      'ulasan_singkat': 'Ati sapi pahit dan santan nangka terlalu berminyak.',
    },
  ];
}
