class MockData {
  // 1. Data Profil Siswa Utama (Faizullatif Fajran - MAN 2 Kota Padang)
  static const Map<String, dynamic> studentProfile = {
    'id': 'usr_991823ab',
    'nisn': '3171012345670001',
    'name': 'Faizullatif Fajran',
    'school': 'MAN 2 Kota Padang',
    'classGrade': 'XII.FA-3',
    'allergies': ['Kacang Tanah', 'Udang'],
    'phone': '081234567890',
  };

  // 2. Data Statistik Ringkasan Dasbor Siswa (Bulan Agustus 2026)
  static const Map<String, dynamic> studentDashboardStats = {
    'totalPortionsReceived': 18,
    'attendancePercentage': 95.0,
    'totalEvaluationsSubmitted': 16,
    'currentDateFormatted': 'Sabtu, 8 Agustus 2026',
  };

  // 3. Master Daftar Menu MBG (12 Katalog Menu Lengkap 100% Sesuai Kontrak API Modul 2)
  static const List<Map<String, dynamic>> foodMenuList = [
    {
      'id_menu': 'mnu_441209cc',
      'nama_menu': 'Nasi Ayam Bakar Kecap & Tumis Buncis',
      'name': 'Nasi Ayam Bakar Kecap & Tumis Buncis',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 550,
      'calories': 550,
      'protein_gram': 28.5,
      'protein': '28.5g',
      'karbohidrat_gram': 65.0,
      'lemak_gram': 14.2,
      'komposisi_bahan': ['Dada Ayam Bakar Kecap', 'Tumis Buncis & Wortel', 'Nasi Putih Warm'],
      'komposisi_bahan_detail': [
        {
          'nama': 'Dada Ayam Bakar Kecap',
          'sub': 'Sumber Utama Protein & Zat Besi',
          'berat': '80 gram',
        },
        {
          'nama': 'Tumis Buncis & Wortel',
          'sub': 'Kaya Serat & Vitamin A',
          'berat': '60 gram',
        },
        {
          'nama': 'Nasi Putih Warm',
          'sub': 'Karbohidrat Kompleks',
          'berat': '150 gram',
        },
      ],
      'potensi_alergen': ['Kedelai'],
      'estimasi_biaya_per_porsi': 15000,
      'foto_url':
          'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
      'photoUrl':
          'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.9,
      'tanggal_jadwal': 'Sabtu, 8 Agustus 2026',
    },
    {
      'id_menu': 'mnu_551902aa',
      'nama_menu': 'Nasi Semur Daging Sapi & Sup Sayur',
      'name': 'Nasi Semur Daging Sapi & Sup Sayur',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 580,
      'calories': 580,
      'protein_gram': 32.0,
      'protein': '32g',
      'karbohidrat_gram': 60.0,
      'lemak_gram': 15.0,
      'komposisi_bahan': [
        'Daging Sapi Empuk Semur',
        'Sup Brokoli & Wortel',
        'Telur Rebus Organik',
        'Nasi Putih Warm'
      ],
      'komposisi_bahan_detail': [
        {
          'nama': 'Daging Sapi Empuk Semur',
          'sub': 'Kaya Asam Amino & Protein Sapi',
          'berat': '90 gram',
        },
        {
          'nama': 'Sup Brokoli & Wortel',
          'sub': 'Antioksidan & Mineral Alami',
          'berat': '70 gram',
        },
        {
          'nama': 'Telur Rebus Organik',
          'sub': 'Sumber Kolin & B12',
          'berat': '50 gram',
        },
        {
          'nama': 'Nasi Putih Warm',
          'sub': 'Karbohidrat Kompleks',
          'berat': '150 gram',
        },
      ],
      'potensi_alergen': ['Kacang Tanah', 'Kedelai'],
      'estimasi_biaya_per_porsi': 16500,
      'foto_url':
          'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
      'photoUrl':
          'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.8,
      'tanggal_jadwal': 'Senin, 10 Agustus 2026',
    },
    {
      'id_menu': 'mnu_662011bb',
      'nama_menu': 'Nasi Ikan Kembung Bakar & Tumis Bayam',
      'name': 'Nasi Ikan Kembung Bakar & Tumis Bayam',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 440,
      'calories': 440,
      'protein_gram': 30.0,
      'protein': '30g',
      'karbohidrat_gram': 52.0,
      'lemak_gram': 10.0,
      'komposisi_bahan': ['Ikan Kembung Bakar', 'Tumis Bayam & Jagung', 'Nasi Putih'],
      'komposisi_bahan_detail': [
        {
          'nama': 'Ikan Kembung Bakar',
          'sub': 'Tinggi Omega-3 & DHA',
          'berat': '85 gram',
        },
        {
          'nama': 'Tumis Bayam & Jagung',
          'sub': 'Asam Folat & Zat Besi',
          'berat': '65 gram',
        },
        {
          'nama': 'Nasi Putih Warm',
          'sub': 'Karbohidrat Utama',
          'berat': '150 gram',
        },
      ],
      'potensi_alergen': ['Ikan Laut'],
      'estimasi_biaya_per_porsi': 14500,
      'foto_url':
          'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      'photoUrl':
          'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.7,
      'tanggal_jadwal': 'Selasa, 11 Agustus 2026',
    },
    {
      'id_menu': 'mnu_773122cc',
      'nama_menu': 'Nasi Rolade Sapi & Capcay Sayur Segar',
      'name': 'Nasi Rolade Sapi & Capcay Sayur Segar',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 520,
      'calories': 520,
      'protein_gram': 26.0,
      'protein': '26g',
      'karbohidrat_gram': 58.0,
      'lemak_gram': 12.5,
      'komposisi_bahan': ['Rolade Daging Sapi', 'Capcay Sayur Kombinasi', 'Nasi Putih'],
      'komposisi_bahan_detail': [
        {
          'nama': 'Rolade Daging Sapi',
          'sub': 'Protein Olahan Berkualitas',
          'berat': '80 gram',
        },
        {
          'nama': 'Capcay Sayur Kombinasi',
          'sub': 'Kembang Kol, Wortel & Sawi',
          'berat': '70 gram',
        },
        {
          'nama': 'Nasi Putih Warm',
          'sub': 'Karbohidrat Utama',
          'berat': '150 gram',
        },
      ],
      'potensi_alergen': ['Telur', 'Kedelai'],
      'estimasi_biaya_per_porsi': 15000,
      'foto_url':
          'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
      'photoUrl':
          'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.8,
      'tanggal_jadwal': 'Rabu, 12 Agustus 2026',
    },
    {
      'id_menu': 'mnu_884233dd',
      'nama_menu': 'Nasi Ayam Goreng Lengkuas & Tahu Tempe',
      'name': 'Nasi Ayam Goreng Lengkuas & Tahu Tempe',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 560,
      'calories': 560,
      'protein_gram': 29.0,
      'protein': '29g',
      'karbohidrat_gram': 62.0,
      'lemak_gram': 16.0,
      'komposisi_bahan': ['Ayam Goreng Rempah', 'Tahu Tempe Goreng', 'Lalapan Segar'],
      'komposisi_bahan_detail': [
        {
          'nama': 'Ayam Goreng Rempah Lengkuas',
          'sub': 'Sumber Protein & Niacin',
          'berat': '85 gram',
        },
        {
          'nama': 'Tahu Tempe Bacem Kukus',
          'sub': 'Isoflavon & Protein Nabati',
          'berat': '50 gram',
        },
        {
          'nama': 'Nasi Putih Warm',
          'sub': 'Karbohidrat Kompleks',
          'berat': '150 gram',
        },
      ],
      'potensi_alergen': ['Kedelai'],
      'estimasi_biaya_per_porsi': 15000,
      'foto_url':
          'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      'photoUrl':
          'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      'rating_rata_rata': 4.9,
      'tanggal_jadwal': 'Kamis, 13 Agustus 2026',
    },
    {
      'id_menu': 'mnu_995344ee',
      'nama_menu': 'Nasi Telur Balado & Tumis Kacang Panjang',
      'name': 'Nasi Telur Balado & Tumis Kacang Panjang',
      'kategori': 'MAKANAN_BERAT',
      'category': 'Makanan Berat',
      'kalori_kkal': 480,
      'calories': 480,
      'protein_gram': 22.0,
      'protein': '22g',
      'karbohidrat_gram': 55.0,
      'lemak_gram': 11.0,
      'komposisi_bahan': ['Telur Balado Merah', 'Tumis Kacang Panjang', 'Tempe Oreg'],
      'komposisi_bahan_detail': [
        {
          'nama': 'Telur Balado Merah',
          'sub': 'Protein Telur Utuh',
          'berat': '60 gram',
        },
        {
          'nama': 'Tumis Kacang Panjang',
          'sub': 'Serat & Vitamin B Kompleks',
          'berat': '60 gram',
        },
      ],
      'potensi_alergen': ['Telur', 'Kedelai'],
      'estimasi_biaya_per_porsi': 13500,
      'foto_url':
          'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
      'photoUrl':
          'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
    },
  ];

  static Map<String, dynamic> get todayMenu => foodMenuList.first;
  static Map<String, dynamic> get tomorrowMenu => foodMenuList[1];

  static List<Map<String, String>> get masterHealthyIngredients =>
      masterHealthyIngredientsFull.map((item) {
        return {
          'nama': item['nama_bahan'].toString(),
          'sub': item['subjudul_nutrisi'].toString(),
          'berat': item['takaran_default'].toString(),
        };
      }).toList();

  static const List<Map<String, dynamic>> masterHealthyIngredientsFull = [
    {
      'id_bahan': 'bhn_10293847',
      'nama_bahan': 'Dada Ayam Bakar Kecap',
      'nama': 'Dada Ayam Bakar Kecap',
      'kategori_bahan': 'PROTEIN_HEWANI',
      'kategori': 'Protein Hewani',
      'subjudul_nutrisi': 'Sumber Utama Protein & Zat Besi',
      'sub': 'Sumber Utama Protein & Zat Besi',
      'takaran_default': '80 gram',
      'berat': '80 gram',
      'kalori_per_100g': 165,
      'potensi_alergen': ['Kedelai'],
    },
    {
      'id_bahan': 'bhn_10293848',
      'nama_bahan': 'Daging Sapi Semur Empuk',
      'nama': 'Daging Sapi Semur Empuk',
      'kategori_bahan': 'PROTEIN_HEWANI',
      'kategori': 'Protein Hewani',
      'subjudul_nutrisi': 'Kaya Asam Amino & Protein Sapi',
      'sub': 'Kaya Asam Amino & Protein Sapi',
      'takaran_default': '90 gram',
      'berat': '90 gram',
      'kalori_per_100g': 250,
      'potensi_alergen': ['Kedelai'],
    },
  ];

  // 7. Master Data Rekomendasi TOPSIS SPK (12 Menu Katalog MBG)
  static const List<Map<String, dynamic>> topsisRecommendations = [
    {
      'id': 'rec_01',
      'nama_menu': 'Nasi Ayam Bakar Kecap & Tumis Buncis',
      'kategori': 'Makanan Berat',
      'kalori': '550 kcal',
      'skor_kepuasan': '96.5%',
      'kepuasan_num': 96.5,
      'skor_rasa': 4.8,
      'skor_kesukaan': 4.9,
      'skor_porsi': 4.7,
      'sisa_makanan_pct': 4.2,
      'penolakan_pct': 2.1,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit Utama (Sangat Disukai Siswa)',
      'idss_insight': 'Berdasarkan survei 425 siswa, rasa gurih bakar kecap mencapai rating 4.9/5. Sisa makanan sangat rendah (4.2%). Sangat direkomendasikan disajikan 2x seminggu.',
      'ulasan_singkat': 'Favorit utama siswa, bumbu meresap & porsi sangat pas.',
    },
    {
      'id': 'rec_02',
      'nama_menu': 'Nasi Semur Daging Sapi & Sup Sayur',
      'kategori': 'Makanan Berat',
      'kalori': '580 kcal',
      'skor_kepuasan': '94.0%',
      'kepuasan_num': 94.0,
      'skor_rasa': 4.7,
      'skor_kesukaan': 4.8,
      'skor_porsi': 4.6,
      'sisa_makanan_pct': 5.0,
      'penolakan_pct': 3.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Penerimaan Tinggi)',
      'idss_insight': 'Tingkat kecukupan protein tinggi (32g). Kombinasi daging empuk dan sup brokoli segar disukai 94% siswa.',
      'ulasan_singkat': 'Daging empuk, sisa makanan sangat rendah di sekolah.',
    },
    {
      'id': 'rec_03',
      'nama_menu': 'Nasi Daging Sapi Lada Hitam & Capcay',
      'kategori': 'Makanan Berat',
      'kalori': '620 kcal',
      'skor_kepuasan': '92.5%',
      'kepuasan_num': 92.5,
      'skor_rasa': 4.6,
      'skor_kesukaan': 4.7,
      'skor_porsi': 4.5,
      'sisa_makanan_pct': 5.5,
      'penolakan_pct': 3.2,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Sangat Baik)',
      'idss_insight': 'Menu energi tinggi cocok untuk jadwal olahraga sekolah. Rasio penerimaan siswa mencapai 92.5%.',
      'ulasan_singkat': 'Rasa lezat, porsi daging mencukupi kebutuhan energi.',
    },
    {
      'id': 'rec_04',
      'nama_menu': 'Nasi Rolade Sapi & Capcay Sayur Segar',
      'kategori': 'Makanan Berat',
      'kalori': '520 kcal',
      'skor_kepuasan': '89.0%',
      'kepuasan_num': 89.0,
      'skor_rasa': 4.5,
      'skor_kesukaan': 4.5,
      'skor_porsi': 4.4,
      'sisa_makanan_pct': 7.0,
      'penolakan_pct': 4.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Baik)',
      'idss_insight': 'Tekstur rolade ramah bagi siswa SD & SMP. Penilaian kepuasan stabil di angka 89%.',
      'ulasan_singkat': 'Rolade empuk, capcay segar tidak berbau langu.',
    },
    {
      'id': 'rec_05',
      'nama_menu': 'Nasi Ayam Goreng Lengkuas & Tahu Tempe',
      'kategori': 'Makanan Berat',
      'kalori': '560 kcal',
      'skor_kepuasan': '86.5%',
      'kepuasan_num': 86.5,
      'skor_rasa': 4.4,
      'skor_kesukaan': 4.4,
      'skor_porsi': 4.3,
      'sisa_makanan_pct': 8.5,
      'penolakan_pct': 4.8,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Baik)',
      'idss_insight': 'Rempah gurih diminati siswa. Disarankan menambah kesegaran lalapan untuk menaikkan rating porsi.',
      'ulasan_singkat': 'Ayam gurih renyah, tahu tempe bacem lembut.',
    },
    {
      'id': 'rec_06',
      'nama_menu': 'Nasi Ikan Kembung Bakar & Tumis Bayam',
      'kategori': 'Makanan Berat',
      'kalori': '440 kcal',
      'skor_kepuasan': '83.0%',
      'kepuasan_num': 83.0,
      'skor_rasa': 4.3,
      'skor_kesukaan': 4.2,
      'skor_porsi': 4.2,
      'sisa_makanan_pct': 10.0,
      'penolakan_pct': 5.2,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Cukup Baik)',
      'idss_insight': 'Sumber Omega-3 tinggi. Beberapa siswa menyarankan pengurangan duri halus pada ikan kembung.',
      'ulasan_singkat': 'Kaya asam omega-3, bumbu bakar meresap.',
    },
    {
      'id': 'rec_07',
      'nama_menu': 'Nasi Telur Balado & Tumis Kacang Panjang',
      'kategori': 'Makanan Berat',
      'kalori': '480 kcal',
      'skor_kepuasan': '79.5%',
      'kepuasan_num': 79.5,
      'skor_rasa': 4.1,
      'skor_kesukaan': 4.0,
      'skor_porsi': 4.0,
      'sisa_makanan_pct': 12.0,
      'penolakan_pct': 6.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Cukup Baik)',
      'idss_insight': 'Menu ekonomis bernutrisi tinggi. Tingkat kepedasan balado telah disesuaikan dengan standar siswa.',
      'ulasan_singkat': 'Telur balado gurih, manis pedas pas di lidah.',
    },
    {
      'id': 'rec_08',
      'nama_menu': 'Nasi Soto Ayam Kuning & Perkedel',
      'kategori': 'Makanan Berat',
      'kalori': '510 kcal',
      'skor_kepuasan': '75.0%',
      'kepuasan_num': 75.0,
      'skor_rasa': 4.0,
      'skor_kesukaan': 3.9,
      'skor_porsi': 3.9,
      'sisa_makanan_pct': 14.5,
      'penolakan_pct': 7.5,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Cukup Baik)',
      'idss_insight': 'Kuah soto hangat disukai saat musim hujan. Perkedel kentang menjadi pelengkap favorit.',
      'ulasan_singkat': 'Kuah soto segar, perkedel gurih dan lembut.',
    },
    {
      'id': 'rec_09',
      'nama_menu': 'Nasi Ikan Gurame Asam Manis & Sup Sayur',
      'kategori': 'Makanan Berat',
      'kalori': '580 kcal',
      'skor_kepuasan': '71.2%',
      'kepuasan_num': 71.2,
      'skor_rasa': 3.9,
      'skor_kesukaan': 3.8,
      'skor_porsi': 3.8,
      'sisa_makanan_pct': 16.0,
      'penolakan_pct': 8.0,
      'keputusan': 'DIPERTAHANKAN',
      'keputusanLabel': 'Menu Favorit (Standar)',
      'idss_insight': 'Menu variasi ikan gurame segar. Saus asam manis perlu dikurangi keasamannya.',
      'ulasan_singkat': 'Ikan gurame renyah, saus asam manis segar.',
    },
    {
      'id': 'rec_10',
      'nama_menu': 'Nasi Tumis Cumi Cabe Hijau & Tahu',
      'kategori': 'Makanan Berat',
      'kalori': '460 kcal',
      'skor_kepuasan': '44.5%',
      'kepuasan_num': 44.5,
      'skor_rasa': 2.9,
      'skor_kesukaan': 2.8,
      'skor_porsi': 3.2,
      'sisa_makanan_pct': 28.5,
      'penolakan_pct': 16.0,
      'keputusan': 'MODIFIKASI_RESEP',
      'keputusanLabel': 'Perlu Evaluasi (Tingkat Kepuasan < 50%)',
      'idss_insight': 'Evaluasi IDSS: Kepuasan di bawah 50% (44.5%) dan sisa makanan tinggi (28.5%). Tekstur cumi terlalu kenyal & pedas bagi siswa.',
      'ulasan_singkat': 'Tekstur cumi agak agal kenyal, cabe hijau terlalu pedas.',
    },
    {
      'id': 'rec_11',
      'nama_menu': 'Nasi Ikan Asin Pedas & Sayur Lodeh',
      'kategori': 'Makanan Berat',
      'kalori': '410 kcal',
      'skor_kepuasan': '38.0%',
      'kepuasan_num': 38.0,
      'skor_rasa': 2.6,
      'skor_kesukaan': 2.5,
      'skor_porsi': 3.0,
      'sisa_makanan_pct': 32.5,
      'penolakan_pct': 22.0,
      'keputusan': 'DIHAPUS_GANTI_MENU',
      'keputusanLabel': 'Perlu Evaluasi (Tingkat Kepuasan < 50%)',
      'idss_insight': 'Evaluasi IDSS: Kepuasan sangat rendah (38.0%) & pemborosan makanan 32.5%. Direkomendasikan ganti menu ikan segar lain.',
      'ulasan_singkat': 'Tingkat asin terlalu tinggi, banyak sisa makanan tak terhabiskan.',
    },
    {
      'id': 'rec_12',
      'nama_menu': 'Nasi Sayur Nangka & Sambal Goreng Ati',
      'kategori': 'Makanan Berat',
      'kalori': '490 kcal',
      'skor_kepuasan': '35.2%',
      'kepuasan_num': 35.2,
      'skor_rasa': 2.4,
      'skor_kesukaan': 2.3,
      'skor_porsi': 3.1,
      'sisa_makanan_pct': 36.0,
      'penolakan_pct': 25.0,
      'keputusan': 'DIHAPUS_GANTI_MENU',
      'keputusanLabel': 'Perlu Evaluasi (Tingkat Kepuasan < 50%)',
      'idss_insight': 'Evaluasi IDSS: Kepuasan terendah (35.2%) dengan penolakan siswa 25%. Disarankan evaluasi total / ganti menu olahan ayam.',
      'ulasan_singkat': 'Ati sapi pahit dan santan nangka terlalu berminyak.',
    },
  ];
}
